services:
  backend:
    build:
      context: ./Backend
    container_name: vaultdrive_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./Backend/app:/app/app
      - ./Backend/alembic:/app/alembic

  db:
    image: postgres:17
    container_name: vaultdrive_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
