"""add deleted_at to files

Revision ID: 7987bf1d1461
Revises: c9666d86bb64
Create Date: 2026-09-15 07:01:20.346099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7987bf1d1461'
down_revision: Union[str, Sequence[str], None] = 'c9666d86bb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_column('files', 'deleted_at')
    # ### end Alembic commands ###
