"""add trash fields to folders

Revision ID: adb2d41c2632
Revises: a8913635bed3
Create Date: 2026-09-15 10:36:36.344397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb2d41c2632'
down_revision: Union[str, Sequence[str], None] = 'a8913635bed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'folders',
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.add_column(
        'folders',
        sa.Column(
            'deleted_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.create_index(
        op.f('ix_folders_is_deleted'),
        'folders',
        ['is_deleted'],
        unique=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_is_deleted'), table_name='folders')
    op.drop_column('folders', 'deleted_at')
    op.drop_column('folders', 'is_deleted')
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
